version: '3'

silent: true

tasks:

  test-dec:
    desc: Runs tests using dec-number feature
    cmds:
      - cmd: cargo test -p dsntk-feel-number --features="dec-number"

  test-dfp:
    desc: Runs tests using dfp-number feature
    cmds:
      - cmd: cargo test -p dsntk-feel-number --features="dfp-number"
