name: apple-macos-x86-64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - run: cargo +stable build --release --target=x86_64-apple-darwin
      - uses: actions/upload-artifact@v3
        with:
          name: dsntk-apple-macos-x86_64
          path: target/x86_64-apple-darwin/release/dsntk
