name: musl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - run: sudo apt-get update && sudo apt-get install -y musl-tools
      - run: cargo build --release --target=x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v3
        with:
          name: dsntk-musl
          path: target/x86_64-unknown-linux-musl/release/dsntk
