# linux-ubuntu-x86_64

name: Ubuntu

on:
  push:
    branches:
      - main
      - releases/**
  pull_request:
    branches:
      - main
      - releases/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - run: cargo +stable build --release --target=x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: dsntk-linux-ubuntu-x86_64
          path: target/x86_64-unknown-linux-gnu/release/dsntk
